### ISSUE TITLE
problem install cimpiler on Ubuntu

### ISSUE THREAD

**Issue by LilachDery** [pulp-platform/ri5cy_gnu_toolchain#11]
hey, i'm trying to run the toolchain, but i got this error and i dont know why?

pulp@ubuntu:~/Desktop/ri5cy_gnu_toolchain-master$ make
if [ ! -e toolchain ]; then git clone
https://github.com/riscv/riscv-gnu-toolchain.git toolchain; fi
/bin/sh: 1: git: not found
make: *** [build] Error 127

**Comment by FrancescoConti** [comment]
`/bin/sh: 1: git: not found`
You have to install `git` to use `git`.

**Comment by LilachDery** [comment]
thank you very much!!

I have installed git, and i got these errors, after i upgraded my ubuntu:

make[5]: Entering directory
/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
make[5]: Nothing to be done forinfo'.
make[5]: Leaving directory
/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
make[5]: Entering directory
/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[5]: Nothing to be done for info-am'. make[5]: Leaving directory
/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[4]: *** [info-recursive] Error 1
make[4]: Leaving directory
/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[3]: *** [all-bfd] Error 2 make[3]: Leaving directory
/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib'
make[2]: *** [all] Error 2
make[2]: Leaving directory
/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib'
make[1]: *** [stamps/build-binutils-newlib] Error 2 make[1]: Leaving
directory/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build'
make: *** [build] Error 2

how to solve that? thanks a lot
