### ISSUE TITLE
Call to virtual functions resulting in jump to 0x0

### ISSUE THREAD

**Issue by deepsrc** [pulp-platform/ri5cy_gnu_toolchain#14]
The compiler provided with PULPino seems to have issue with virtual functions. A call to a virtual functions causes a jump to 0x0.

Compiler details:
#->riscv32-unknown-elf-g++ -v
Using built-in specs.
COLLECT_GCC=riscv32-unknown-elf-g++
COLLECT_LTO_WRAPPER=/media/sthiruva/13cd6a3c-12da-4d2e-92e3-3554d87485dd/pulp-tools/ri5cy_gnu_toolchain/install/libexec/gcc/riscv32-unknown-elf/5.2.0/lto-wrapper
Target: riscv32-unknown-elf
Configured with: /media/sthiruva/13cd6a3c-12da-4d2e-92e3-3554d87485dd/pulp-tools/ri5cy_gnu_toolchain/build/src/newlib-gcc/configure --target=riscv32-unknown-elf --prefix=/media/sthiruva/13cd6a3c-12da-4d2e-92e3-3554d87485dd/pulp-tools/ri5cy_gnu_toolchain/install --disable-shared --disable-threads --enable-tls --enable-languages=c,c++ --with-newlib --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --disable-multilib --with-arch=IM
Thread model: single
gcc version 5.2.0 (GCC)

**Comment by haugoug** [comment]
The runtime we provide for pulpino does not support C++, there are probably some issues to fix with the C++ runtime initialization.
