### ISSUE TITLE
Error: unknown arch

### ISSUE THREAD

**Issue by thotaraghava** [pulp-platform/ri5cy_gnu_toolchain#17]
Hi anybody,

    I was trying to run make to install toolchain for pulpino simulations and I end up by getting below error.

           configure: error: Unknown arch

   Please help in this regard.

Thanks,

**Comment by thotaraghava** [comment]
Anybody knows this issue ??

**Comment by thotaraghava** [comment]
I am clueless on this issue.

**Comment by FrancescoConti** [comment]
Hi @thotaraghava, it seems to me that it might be a problem with your compiler, but you should post a more detailed log and write _exactly_ what you are doing (including the platform you're running on).

**Comment by thotaraghava** [comment]
Thanks @FrancescoConti  for your response.
I am doing exactly the procedure mentioned in the below link.
https://github.com/pulp-platform/ri5cy_gnu_toolchain

I am running make command to install toolchain.

I want to simulate PULPino core with testcases, for that I need to install toolchain.

Kindly help.

**Comment by FrancescoConti** [comment]
Ok. Can you provide a full log from when you type `make` up to the error?
  
Edit: Also, please let us know the platform you're running on (e.g. version of Ubuntu)

**Comment by thotaraghava** [comment]
```
#if [ ! -e toolchain ]; then git clone https://github.com/r
#cd toolchain && git checkout d038d596dc1d8e47ace22ab742cd40c2f22d659e
#cd toolchain
if [ -d  ]; then \
cd toolchain; \
FILES=$(ls /*.patch | sort); \
for tmp in $FILES; do \
test=$(patch -p1 -R -N --dry-run <$tmp 1>/dev/null 2>&1; echo $?);  \
if [ "$test" != "0" ]; then patch -p1 -N <$tmp; fi \
done; \
fi
ls: cannot access /*.patch: No such file or directory
mkdir -p /user/<user>/ri5cy_gnu_toolchain/build
configure: WARNING: unrecognized options: --with-xlen, --disable-float
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for grep that handles long lines and -e... /bin/grep
checking for fgrep... /bin/grep -F
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for bash... /bin/sh
checking for __gmpz_init in -lgmp... yes
hecking for mpfr_init in -lmpfr... yes
checking for mpc_init2 in -lmpc... no
checking for curl... /usr/bin/curl
checking for wget... /usr/bin/wget
checking for ftp... /usr/bin/ftp
configure: WARNING: unrecognized options: --with-xlen, --disable-float
configure: error: Unknown arch
make: *** [build] Error 1
```

**Comment by thotaraghava** [comment]
First two lines in make file I commented because, I we dont have access internet on VWP, so I downloaded separately and copied down to working area.

**Comment by thotaraghava** [comment]
I am running on LINUX environment.

**Comment by FrancescoConti** [comment]
Which distribution of Linux and which version?

**Comment by thotaraghava** [comment]
LSB_VERSION=base-4.0-amd64:base-4.0-ia32:base-4.0-noarch:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch

Red Hat Enterprise Linux Server release 6.6 (Santiago)

Distributor ID:	RedHatEnterpriseServer
Release:	6.6

Is this info enough ?
Let me know if you need any more information

**Comment by FrancescoConti** [comment]
Ok, can you also share the version of GCC (`gcc --version`)?

**Comment by thotaraghava** [comment]
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOS

**Comment by thotaraghava** [comment]
@FrancescoConti , please let me know your opinion.

Thanks

**Comment by FrancescoConti** [comment]
Initially I thought there was a problem with your setup, but actually the solution might be simpler. Can you check whether the version of the toolchain you downloaded from Berkeley is correct? You can do that by the following command:
```
cd toolchain
git rev-parse --short HEAD
```

The output must be `d038d59`. If not, then you have to redownload the correct version from their repo.

**Comment by thotaraghava** [comment]
7df3261

This is the one, I am getting. Then I should re-download I suppose.
@FrancescoConti 
 Below the one I should re-download right.
https://github.com/riscv/riscv-gnu-toolchain
  
Re-downloading correct version means from the above link only right.
I did the same. How could I make sure its correct version. Please suggest.

I understood. From the commented line in Makefile
#cd toolchain && git checkout d038d596dc1d8e47ace22ab742cd40c2f22d659e,
your version suggested is matching with initial portion of above checkout version.
Then, how can I make sure same version download in Windows as I dont have internet access to my VWP.

**Comment by thotaraghava** [comment]
@FrancescoConti , any update on this

**Comment by FrancescoConti** [comment]
If version `d038d59` is in the history of their master branch (I don't know whether that is so), you can uncomment that line in the Makefile (or simply execute that same line in the shell).

On a side note, this really does not look like a problem with this project, so I'm going to flag the issue as closed.

**Comment by thotaraghava** [comment]
Thank you.
