### ISSUE TITLE
Error when running the make command

### ISSUE THREAD

**Issue by sourav1394** [pulp-platform/ri5cy_gnu_toolchain#18]
I'm getting the following error when I run the make command:

In file included from /home/sourav/Desktop/HackDAC/ri5cy_gnu_toolchain/build/src/newlib-gcc/gcc/cp/except.c:1023:0:
cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
make[4]: *** [cp/except.o] Error 1
make[4]: Leaving directory `/home/sourav/Desktop/HackDAC/ri5cy_gnu_toolchain/build/build-gcc-newlib/gcc'
make[3]: *** [all-gcc] Error 2
make[3]: Leaving directory `/home/sourav/Desktop/HackDAC/ri5cy_gnu_toolchain/build/build-gcc-newlib'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/sourav/Desktop/HackDAC/ri5cy_gnu_toolchain/build/build-gcc-newlib'
make[1]: *** [stamps/build-gcc-newlib] Error 2
make[1]: Leaving directory `/home/sourav/Desktop/HackDAC/ri5cy_gnu_toolchain/build'
make: *** [build] Error 2

Running it on Ubuntu 14.04 with gcc 7.2.

How do I fix this?

**Comment by haugoug** [comment]
We have never seen this issue before. We are using gcc 5.2, probably gcc 7.2 is bringing some issues. Let us know if you find any solution.

**Comment by sourav1394** [comment]
Tried it directly from https://github.com/riscv/riscv-gnu-toolchain
Made the following change while configuring:
./configure --with-arch=rv32i --disable-atomic --disable-multilib --prefix=path/to/install
Seems to be working.

**Comment by nasahlpa** [comment]
problem can be solved using the fix from this link [1]

[1]: https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=ec1cc0263f156f70693a62cf17b254a0029f4852
