### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by ghost** [pulp-platform/ri5cy_gnu_toolchain#20]
Hello,

I'm taking these. Any idea would be appreciated!

In file included from /run/media/kllbrd/work/PULP/pulpino/riscv/ri5cy_gnu_toolchain/build/src/newlib-gcc/gcc/cp/except.c:1023:0:
cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
Makefile:1064: recipe for target 'cp/except.o' failed
make[4]: *** [cp/except.o] Error 1
make[4]: Leaving directory '/run/media/kllbrd/work/PULP/pulpino/riscv/ri5cy_gnu_toolchain/build/build-gcc-newlib/gcc'
Makefile:4112: recipe for target 'all-gcc' failed
make[3]: *** [all-gcc] Error 2
make[3]: Leaving directory '/run/media/kllbrd/work/PULP/pulpino/riscv/ri5cy_gnu_toolchain/build/build-gcc-newlib'
Makefile:867: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/run/media/kllbrd/work/PULP/pulpino/riscv/ri5cy_gnu_toolchain/build/build-gcc-newlib'
Makefile:214: recipe for target 'stamps/build-gcc-newlib' failed
make[1]: *** [stamps/build-gcc-newlib] Error 2
make[1]: Leaving directory '/run/media/kllbrd/work/PULP/pulpino/riscv/ri5cy_gnu_toolchain/build'
Makefile:28: recipe for target 'build' failed
make: *** [build] Error 2

My gcc version:

[root@localhost ri5cy_gnu_toolchain]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --with-isl --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC)

**Comment by haugoug** [comment]
You can try with the new toolchain here, this may disappear:
https://github.com/pulp-platform/pulp-riscv-gnu-toolchain

**Comment by shivanandchidri** [comment]
Fatal error: -Xpulpv2: pulp architecture is already defined as riscv
Makefile:466: recipe for target '_muldi3.o' failed
make[3]: *** [_muldi3.o] Error 1
make[3]: Leaving directory '/root/pulpino/ri5cy_gnu_toolchain/build/build-gcc-newlib/riscv32-unknown-elf/libgcc'
Makefile:11674: recipe for target 'all-target-libgcc' failed
make[2]: *** [all-target-libgcc] Error 2
make[2]: Leaving directory '/root/pulpino/ri5cy_gnu_toolchain/build/build-gcc-newlib'
Makefile:867: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/pulpino/ri5cy_gnu_toolchain/build/build-gcc-newlib'
Makefile:28: recipe for target 'build' failed
make: *** [build] Error 2
root@shivanand-Extensa-M200-H110:~/pulpino/ri5cy_gnu_toolchain# sudo make install
make: Nothing to be done for 'install'.
root@shivanand-Extensa-M200-H110:~/pulpino/ri5cy_gnu_toolchain# ./configure 
-bash: ./configure: No such file or directory
root@shivanand-Extensa-M200-H110:~/pulpino/ri5cy_gnu_toolchain# /configure --enable-lenient
-bash: /configure: No such file or directory
root@shivanand-Extensa-M200-H110:~/pulpino/ri5cy_gnu_toolchain# sed -i.bak 's_#include <execinfo.h>_/*#include <execinfo.h>*/_' ${BUILD_DIR}/binutils-${VERSION_BINUTILS}/gas/config/tc-riscv.c

ANS:THIER IS NO ISSUE

**Comment by shivanandchidri** [comment]
Fatal error: -Xpulpv2: pulp architecture is already defined as riscv
Makefile:466: recipe for target '_muldi3.o' failed
make[3]: *** [_muldi3.o] Error 1
make[3]: Leaving directory '/root/pulpino/ri5cy_gnu_toolchain/build/build-gcc-newlib/riscv32-unknown-elf/libgcc'
Makefile:11674: recipe for target 'all-target-libgcc' failed
make[2]: *** [all-target-libgcc] Error 2
make[2]: Leaving directory '/root/pulpino/ri5cy_gnu_toolchain/build/build-gcc-newlib'
Makefile:867: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/pulpino/ri5cy_gnu_toolchain/build/build-gcc-newlib'
Makefile:28: recipe for target 'build' failed
make: *** [build] Error 2
ANS: their is no issue continue with  make MICRORISCY=1
