### ISSUE TITLE
Assertion failure in md_apply_fix at gas/config/tc-riscv.c line 2205

### ISSUE THREAD

**Issue by deepsrc** [pulp-platform/ri5cy_gnu_toolchain#21]
1 out of 20 builds are failing with the following issue.

riscv32-unknown-elf-g++ -x assembler-with-cpp -c -mcmodel=medany -Isrc/include -Isrc/.gen -Isrc/emitted -Isrc/.gen/Conf2Cpp -Isrc/kernel/rv/ -march=RV32IMAFDC -ggdb -DRV32 -o src/.gen/test_0.o src/.gen/test_0.s
src/.gen/test_0.s: Assembler messages:
src/.gen/test_0.s:338: Error: register value used as expression
/tmp/cc9Kguoc.s: Internal error!
Assertion failure in md_apply_fix at /media/sthiruva/13cd6a3c-12da-4d2e-92e3-3554d87485dd/pulp-tools/ri5cy_gnu_toolchain/build/src/binutils/gas/config/tc-riscv.c line 2205.
Please report this bug.

I have renamed the .s files as .s.txt to allow upload. Kindly rename it before trying to recreate this issue.

[test_helper_macros.s.txt](https://github.com/pulp-platform/ri5cy_gnu_toolchain/files/1688572/test_helper_macros.s.txt)
[test_0.s.txt](https://github.com/pulp-platform/ri5cy_gnu_toolchain/files/1688573/test_0.s.txt)

**Comment by haugoug** [comment]
Could you please try with the new toolchain here and reopenthe issue there if it still exist:
https://github.com/pulp-platform/pulp-riscv-gnu-toolchain

**Comment by deepsrc** [comment]
I am getting this error on updating the submodules. Can you please tell
what is wrong?

deepsrc@deepsrc-lenovo:~/Work/Sandboxes/pulp-tools/pulp-riscv-gnu-toolchain$
git submodule update --init --recursive
Submodule 'riscv-binutils-gdb'
(git@github.com:pulp-platform/pulp-riscv-binutils-gdb.git)
registered for path 'riscv-binutils-gdb'
Submodule 'riscv-dejagnu' (https://github.com/riscv/riscv-dejagnu.git)
registered for path 'riscv-dejagnu'
Submodule 'riscv-gcc' (git@github.com:pulp-platform/pulp-riscv-gcc.git)
registered for path 'riscv-gcc'
Submodule 'riscv-glibc' (https://github.com/riscv/riscv-glibc.git)
registered for path 'riscv-glibc'
Submodule 'riscv-newlib' (git@github.com:pulp-platform/pulp-riscv-newlib.git)
registered for path 'riscv-newlib'
Cloning into 'riscv-binutils-gdb'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of
known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pulp-platform/pulp-riscv-binutils-gdb.git'
into submodule path 'riscv-binutils-gdb' failed

**Comment by haugoug** [comment]
The top module was using ssh for submodules so you had to add an ssh key to make it work.
I've just pushed modifications to use https instead so if you update, this should now be fine.

**Comment by deepsrc** [comment]
I ran all the steps from scratch but still end up getting this -

deepsrc@deepsrc-lenovo:~/Work/Sandboxes/pulp-tools/pulp-riscv-gnu-toolchain$
git submodule update --init --recursive
Cloning into 'riscv-binutils-gdb'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pulp-platform/pulp-riscv-binutils-gdb.git'
into submodule path 'riscv-binutils-gdb' failed
deepsrc@deepsrc-lenovo
:~/Work/Sandboxes/pulp-tools/pulp-riscv-gnu-toolchain$

**Comment by haugoug** [comment]
Oops sorry the modification was not pushed, can you try again from scratch ?

**Comment by deepsrc** [comment]
Looks fine now.

Thanks,
Shubhodeep

**Comment by deepsrc** [comment]
I am able to build the toolchain and use it. I have a question. My old
software build setup was using *-march=IMXpulpv2. *What is the exact
replacement for the same in the new toolchain?

Regards,
Shubhodeep

**Comment by haugoug** [comment]
For riscy core you have to use this option: rv32imcxpulpv2
The old option -mrvc should also be removed.

**Comment by deepsrc** [comment]
Okay. Thanks.

**Comment by deepsrc** [comment]
Hi,

All the issues filed by us seem to have gone with the new toolchain. Our
regressions are running clean now. :-)

Thanks,
Shubhodeep

**Comment by haugoug** [comment]
Good I close the tracker
