### ISSUE TITLE
How to enable compression with IMXpulpv2

### ISSUE THREAD

**Issue by desai35** [pulp-platform/ri5cy_gnu_toolchain#25]
Hi,

I built the ri5cy_gnu_toolchain using make and was able to run the IMXpulpv2 option . Is there any way to add the "c" option to enable compression with this option. 

The standard riscv options like "rv32ic" come with the "c" to enable compression. WHen i try to add the "c" in the end of IMXpulpv2, it gives the following error:

cc1: error: -march=IMXpulpv2c: unsupported ISA substring c
make: *** [../../wlan/src/mem_mgmt/mem_mgmt.o] Error 1

Thanks

**Comment by haugoug** [comment]
The option is -mrvc. That's because this toolchain is quite old. You can use option -march=imcxpulpv2 if you switch to this toolchain: https://github.com/pulp-platform/pulp-riscv-gnu-toolchain
