### ISSUE TITLE
Error from ld (logged in build/config.log) -- cannot find -lgmp

### ISSUE THREAD

**Issue by edcarstens** [pulp-platform/ri5cy_gnu_toolchain#3]
This failed to install for me. I found the following error in build/config.log:
...
configure:2866: gcc -o conftest -g -02   conftest.c -lgmp  >&5
/usr/bin/ld: cannot find -lgmp
collect2: ld returned 1 exit status
...

**Comment by edcarstens** [comment]
Another error that shows up from running make in toolchain says:

WARNING: 'makeinfo' is missing on your system..
make[4]: **\* [bfd.info] Error 1

**Comment by gautschimi** [comment]
it doesnt find the gmp library, you definitely have this somewhere on your system. just try to locate it

**Comment by edcarstens** [comment]
My CAD person was successful in installing this
