### ISSUE TITLE
make 

### ISSUE THREAD

**Issue by Nagatejapallapu** [pulp-platform/ri5cy_gnu_toolchain#41]
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:67: recipe for target 'src/original-newlib' failed
make[1]: *** [src/original-newlib] Error 2
make[1]: Leaving directory '/home/pulpino/ri5cy_gnu_toolchain/build'
Makefile:28: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by FrancescoConti** [comment]
I already closed two issues from you (#39 #40).
Dropping terminal output here with no context, no comment, no question will not result in anybody helping you -- this is not Google Search, you have to be descriptive, clear and specific, and post only if you have issues actually related to this code, which is very probably not your case.

Duplicating issues is bad, reopening without any additional comment is even worse.
I am going to close this issue as well. Next time, I'll block your user. You have been advised.
