### ISSUE TITLE
Support for std::thread?

### ISSUE THREAD

**Issue by micheleportolan** [pulp-platform/ri5cy_gnu_toolchain#5]
I am trying to build a project that works on both amd64 and arm, but with this toolchain I get this error:

error: 'thread' in namespace 'std' does not name a type
       std::thread::id     _call_thread_id;

Is there a way to enable this feature?

Best regards,

Michele

**Comment by haugoug** [comment]
We don't have any threading support so you have to do it from scratch if 
you want to implement threading. Moreover this feature is part of C+11 
which we don't support.

Best regards,

Germain
