### ISSUE TITLE
Fail to make toolchain

### ISSUE THREAD

**Issue by barry41409** [pulp-platform/ri5cy_gnu_toolchain#6]
hi,everyone
I clone the ri5cy_gnu_toolchain and make it.
(version: ubuntu 12.04 32bit)
how can I fix error?
can't support 32bit?

WARNING: `makeinfo' is missing on your system.  You should only need it if
         you modified a `.texi' or `.texinfo' file, or any other file
         indirectly affecting the aspect of the manual.  The spurious
         call might also be the consequence of using a buggy `make' (AIX,
         DU, IRIX).  You might want to install the `Texinfo' package or
         the `GNU make' package.  Grab either from any GNU archive site.
make[5]: *** [bfd.info] Error 1
make[5]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/doc'
Making info in po
make[5]: Entering directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
( if test 'x/home/lab526/ri5cy_gnu_toolchain-master/build/src/binutils/bfd/po' != 'x.'; then \
	    posrcprefix='/home/lab526/ri5cy_gnu_toolchain-master/build/src/binutils/bfd/'; \
	  else \
	    posrcprefix="../"; \
	  fi; \
	  rm -f SRC-POTFILES-t SRC-POTFILES \
	    && (sed -e '/^#/d' \
	            -e '/^[ 	]*$/d' \
		    -e "s@.*@	$posrcprefix& \\\\@" < /home/lab526/ri5cy_gnu_toolchain-master/build/src/binutils/bfd/po/SRC-POTFILES.in \
		| sed -e '$s/\\$//') > SRC-POTFILES-t \
	    && chmod a-w SRC-POTFILES-t \
	    && mv SRC-POTFILES-t SRC-POTFILES )
( rm -f BLD-POTFILES-t BLD-POTFILES \
	    && (sed -e '/^#/d' \
	            -e '/^[ 	]*$/d' \
		    -e "s@.*@	../& \\\\@" < /home/lab526/ri5cy_gnu_toolchain-master/build/src/binutils/bfd/po/BLD-POTFILES.in \
		| sed -e '$s/\\$//') > BLD-POTFILES-t \
	    && chmod a-w BLD-POTFILES-t \
	    && mv BLD-POTFILES-t BLD-POTFILES )
cd .. \
	  && CONFIG_FILES=po/Makefile.in:po/Make-in \
	     CONFIG_HEADERS= /bin/bash ./config.status
config.status: creating po/Makefile.in
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing bfd_stdint.h commands
config.status: executing default commands
make[5]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
make[5]: Entering directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
make[5]: Nothing to be done for `info'.
make[5]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
make[5]: Entering directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[5]: Nothing to be done for `info-am'.
make[5]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[4]: *** [info-recursive] Error 1
make[4]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[3]: *** [all-bfd] Error 2
make[3]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build/build-binutils-newlib'
make[1]: *** [stamps/build-binutils-newlib] Error 2
make[1]: Leaving directory `/home/lab526/ri5cy_gnu_toolchain-master/build'
make: *** [build] Error 2

**Comment by haugoug** [comment]
Hi,
you seem to miss some packages, you should try to install what the build process is advising you like texinfo.

**Comment by barry41409** [comment]
hi,thanks your reply.My name is Barry.
I installed texinfo in the afternoon but the same error can't be solved.
What package can I miss?
Do you have same problem?
[image: 內置圖片 1]


2017-03-04 15:58 GMT+08:00 haugoug <notifications@github.com>:

**Comment by haugoug** [comment]
Probably it is because of your old Ubuntu distribution you should try to 
update it.

**Comment by barry41409** [comment]
hi,I am update Ubuntu version,but I meet same problem.
if I use 64bit version,this problem can't appear.
Does the toolchain suport 64bit?

ps. I have some problem about modelsim's path in 64bit.

thanks

2017-03-08 6:07 GMT+08:00 haugoug <notifications@github.com>:

**Comment by haugoug** [comment]
Yes it is possible that it is due to the 32bits, we only test with 
64bits machines.

**Comment by zejiang0jason** [comment]
I found a workaround for the 32-bit PC. Modify the Makefile like this:

`cd toolchain && git checkout -f d038d596dc1d8e47ace22ab742cd40c2f22d659e && git cherry-pick 9870cf9b04263de8173aacc17ebd07c31f3011ef`

**Comment by LilachDery** [comment]
hey, i got almost the same errors, I did upgrade to ubuntu, but i got the same errors:

make[5]: Entering directory
`/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
make[5]: Nothing to be done for `info'.
make[5]: Leaving directory
`/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd/po'
make[5]: Entering directory
`/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[5]: Nothing to be done for `info-am'.
make[5]: Leaving directory
`/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[4]: *** [info-recursive] Error 1
make[4]: Leaving directory
`/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib/bfd'
make[3]: *** [all-bfd] Error 2
make[3]: Leaving directory
`/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib'
make[2]: *** [all] Error 2
make[2]: Leaving directory
`/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build/build-binutils-newlib'
make[1]: *** [stamps/build-binutils-newlib] Error 2
make[1]: Leaving directory `/home/pulp/Desktop/ri5cy_gnu_toolchain-master/build'
make: *** [build] Error 2

how to solve that? thanks a lot

**Comment by haugoug** [comment]
Have you tried the workaround mentioned above ?

**Comment by LilachDery** [comment]
yes, and I have got this:

>pulp@ubuntu:~/Desktop/toolchain$ cd toolchain && git checkout -f d038d596dc1d8e47ace22ab742cd40c2f22d659e && git cherry-pick 9870cf9b04263de8173aacc17ebd07c31f3011ef
HEAD is now at d038d59... Update to hopefully-final RVC 1.9 encoding
[detached HEAD 1ec2e6a] binutils: attempt to fix bfd on 32-bit machines
 Author: Andrew Waterman <waterman@cs.berkeley.edu>
 1 file changed, 2 insertions(+), 3 deletions(-)

**Comment by haugoug** [comment]
And what happens when you recompile ?

**Comment by LilachDery** [comment]
when I am running the command:
cd toolchain && git checkout -f d038d596dc1d8e47ace22ab742cd40c2f22d659e && git cherry-pick 9870cf9b04263de8173aacc17ebd07c31f3011ef

this what I have got:

HEAD is now at d038d59... Update to hopefully-final RVC 1.9 encoding
[detached HEAD 1ec2e6a] binutils: attempt to fix bfd on 32-bit machines
Author: Andrew Waterman waterman@cs.berkeley.edu
1 file changed, 2 insertions(+), 3 deletions(-)

**Comment by LilachDery** [comment]
and after that, when I am running the command: make
I have got these errors:

make[5]: Leaving directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib/bfd/po'
make[5]: Entering directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib/bfd/po'
make[5]: Nothing to be done for `info'.
make[5]: Leaving directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib/bfd/po'
make[5]: Entering directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib/bfd'
make[5]: Nothing to be done for `info-am'.
make[5]: Leaving directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib/bfd'
make[4]: *** [info-recursive] Error 1
make[4]: Leaving directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib/bfd'
make[3]: *** [all-bfd] Error 2
make[3]: Leaving directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/pulp/Desktop/toolchain/build/build-binutils-newlib'
make[1]: *** [stamps/build-binutils-newlib] Error 2
make[1]: Leaving directory `/home/pulp/Desktop/toolchain/build'
make: *** [build] Error 2

**Comment by LilachDery** [comment]
I am working on ubuntu 13.04

**Comment by haugoug** [comment]
I think it is time to update your system, this version of Ubuntu is not supported anymore since 2014. The best is to use the last LTS version, 16.04.

**Comment by caifuxi** [comment]
Install `makeinfo` using following command:
`sudo apt-get install texinfo`

This solve my issue
