### ISSUE TITLE
Instruction set simulator

### ISSUE THREAD

**Issue by manojcs26** [pulp-platform/ri5cy_gnu_toolchain#7]
Can I know if there is any instruction set simulator for this tool-chain as there is **SPIKE** for the official tool-chain...?
I wanted to run the C code compiled with this toolchain....?

Any help would be appreciated..
Thank you in advance.

Manoj C S

**Comment by haugoug** [comment]
Hi,

we are planning to release one before the end of the year but it is not 
ready yet.

Best regards,

Germain

**Comment by manojcs26** [comment]
Thanks for the information...

with regards
Manoj C S
