### ISSUE TITLE
Build error with 32-bit PC

### ISSUE THREAD

**Issue by zejiang0jason** [pulp-platform/ri5cy_gnu_toolchain#8]
Hi,

I got such error when I tried to build the toolchain on 32-bit linux:

![image](https://user-images.githubusercontent.com/31212062/29520693-befac912-86b4-11e7-84e3-8b227f3e09c5.png)

When build with 64-bit linux, it is OK. Is there any special settings for 32-bit PC?

Thanks a lot.

B.R.
Zejiang

**Comment by haugoug** [comment]
Hi,

no there is no special setting, but we have never built the toolchain on 
32-bit Linux there may indeed be some issues.

Best,

Germain

**Comment by zejiang0jason** [comment]
Hi Germain,

Thanks for your reply.

Is there 32-bit PC support plan?

Another question is, does the toolchain supports multi-lib? In other words, I want to build one copy of toolchain with all libs, when build application, I can specify which lib to link by adding the linker options.

Thanks.

**Comment by haugoug** [comment]
Hi,
sorry for my very late answer. You can move to the new toolchain here, it supports multi-lib:
https://github.com/pulp-platform/pulp-riscv-gnu-toolchain
