### ISSUE TITLE
FPU instruction question

### ISSUE THREAD

**Issue by zejiang0jason** [pulp-platform/ri5cy_gnu_toolchain#9]
Hi,

When I tried the FPU, I found double float instruction "fmv.d" in my image then the core ran to illegal instruction error. I guess this is because of the 'D' flag in toolchain build option "-march=IMFDXpulpv2". But when I changed to "-march=IMFXpulpv2", I got such build error

> cc1: error: -march=IMFXpulpv2: single-precision-only is not yet supported

How can I configure the toolchain to remove the double float instructions? Thanks.

B.R.
Zejiang

**Comment by haugoug** [comment]
Hi,

indeed there is a limitation of the toolchain which only supports both 
floats and doubles but not only floats. Until this is fixed, there are 2 
work-arounds:

- Either make sure that you have no double in your code by always using 
floats constants (e.g. 1.20f), calling float functions (e.g. cosf) and 
using only float type.

- Or use this option to map doubles to floats: -mfpdouble=float . There 
is also this option available to have constants being floats: - 
-fsingle-precision-constant

Best,

Germain

**Comment by zejiang0jason** [comment]
Hi Germain,

Thanks a lot for your answer.

The work-around are workable but not so convenient, the code must be updated and not sure whether the functionality will be impacted. 

Is there toolchain update plan for this?

Thanks again.

**Comment by haugoug** [comment]
Yes indeed this is just a temporary work-around, this is planned to get 
rid of this issue but I cannot tell yet when this is done.

Germain

**Comment by zejiang0jason** [comment]
Hi Germain,

OK, thanks.
